import "./globals.css";
import { Inter } from "next/font/google";

import { CartContainer } from "./(components)/Cart";
import Header from "./(components)/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CartContainer>
      <html lang="en">
        <body className={inter.className}>
          <main className="mx-auto max-w-2xl px-4 sm:px-6 lg:max-w-7xl lg:px-8">
            <Header />
            {children}
          </main>
        </body>
      </html>
    </CartContainer>
  );
}
